export const NAV_LINKS = [
  { label: 'Home', href: '/' },
  { label: 'Inventory', href: '/inventory' },
  { label: 'Financing', href: '/financing' },
  { label: 'Import Duty', href: '/import-duty' },
  { label: 'After-Sales', href: '/after-sales' },
  { label: 'Sell Your Car', href: '/sell' },
  { label: 'About', href: '/about' },
  { label: 'Contact', href: '/contact' },
];

export const FEATURED_VEHICLES = [
  {
    id: 1,
    name: 'Mercedes-Benz GLE 450',
    year: 2021,
    mileage: '38,400 km',
    price: 'KES 8,950,000',
    monthly: 'KES 148,500/mo',
    image: '/images/vehicles/mercedes-gle-450.jpg',
    badges: ['Verified Mileage', 'NTSA Cleared'],
  },
  {
    id: 2,
    name: 'Toyota Land Cruiser Prado',
    year: 2020,
    mileage: '52,100 km',
    price: 'KES 7,200,000',
    monthly: 'KES 119,800/mo',
    image: '/images/vehicles/toyota-prado.jpg',
    badges: ['Verified Mileage', 'Locally Assembled'],
  },
  {
    id: 3,
    name: 'BMW X5 xDrive40i',
    year: 2021,
    mileage: '41,700 km',
    price: 'KES 9,400,000',
    monthly: 'KES 156,200/mo',
    image: '/images/vehicles/bmw-x5.jpg',
    badges: ['Verified Mileage', 'Service History'],
  },
  {
    id: 4,
    name: 'Range Rover Sport HSE',
    year: 2020,
    mileage: '46,900 km',
    price: 'KES 11,200,000',
    monthly: 'KES 185,900/mo',
    image: '/images/vehicles/range-rover-sport.jpg',
    badges: ['Verified Mileage', 'Accident-Free'],
  },
  {
    id: 5,
    name: 'Audi Q7 55 TFSI',
    year: 2021,
    mileage: '35,200 km',
    price: 'KES 9,800,000',
    monthly: 'KES 162,700/mo',
    image: '/images/vehicles/audi-q7.jpg',
    badges: ['Verified Mileage', 'NTSA Cleared'],
  },
  {
    id: 6,
    name: 'Porsche Cayenne S',
    year: 2020,
    mileage: '39,800 km',
    price: 'KES 12,600,000',
    monthly: 'KES 209,100/mo',
    image: '/images/vehicles/porsche-cayenne.jpg',
    badges: ['Verified Mileage', 'Service History'],
  },
];

export const TRUST_BADGES = [
  'NTSA Registered',
  'TIMS Verified',
  'Mileage Guaranteed',
  'Financing from 10%',
  'Nationwide Delivery',
];