// ============================================================
//  Vehicle inventory  single source of truth
//  For now this is local data. Later this will come from
//  Sanity / Postgres. The shape stays the same.
// ============================================================

export type BodyType = 'SUV' | 'Sedan' | 'Pickup' | 'Hatchback' | 'Van';
export type Fuel = 'Petrol' | 'Diesel' | 'Hybrid' | 'EV';
export type Transmission = 'Automatic' | 'Manual';

export interface Vehicle {
  id: number;
  name: string;
  make: string;
  year: number;
  mileageKm: number;
  mileageLabel: string;
  price: number;
  priceLabel: string;
  monthly: number;
  monthlyLabel: string;
  bodyType: BodyType;
  fuel: Fuel;
  transmission: Transmission;
  drive: '2WD' | '4WD' | 'AWD';
  image: string;
  badges: string[];
}

export const VEHICLES: Vehicle[] = [
  {
    id: 1,
    name: 'Mercedes-Benz GLE 450',
    make: 'Mercedes-Benz',
    year: 2021,
    mileageKm: 38400,
    mileageLabel: '38,400 km',
    price: 8950000,
    priceLabel: 'KES 8,950,000',
    monthly: 148500,
    monthlyLabel: 'KES 148,500/mo',
    bodyType: 'SUV',
    fuel: 'Petrol',
    transmission: 'Automatic',
    drive: 'AWD',
    image: '/images/vehicles/mercedes-gle-450.jpg',
    badges: ['Verified Mileage', 'NTSA Cleared'],
  },
  {
    id: 2,
    name: 'Toyota Land Cruiser Prado',
    make: 'Toyota',
    year: 2020,
    mileageKm: 52100,
    mileageLabel: '52,100 km',
    price: 7200000,
    priceLabel: 'KES 7,200,000',
    monthly: 119800,
    monthlyLabel: 'KES 119,800/mo',
    bodyType: 'SUV',
    fuel: 'Diesel',
    transmission: 'Automatic',
    drive: '4WD',
    image: '/images/vehicles/toyota-prado.jpg',
    badges: ['Verified Mileage', 'Locally Assembled'],
  },
  {
    id: 3,
    name: 'BMW X5 xDrive40i',
    make: 'BMW',
    year: 2021,
    mileageKm: 41700,
    mileageLabel: '41,700 km',
    price: 9400000,
    priceLabel: 'KES 9,400,000',
    monthly: 156200,
    monthlyLabel: 'KES 156,200/mo',
    bodyType: 'SUV',
    fuel: 'Petrol',
    transmission: 'Automatic',
    drive: 'AWD',
    image: '/images/vehicles/bmw-x5.jpg',
    badges: ['Verified Mileage', 'Service History'],
  },
  {
    id: 4,
    name: 'Range Rover Sport HSE',
    make: 'Land Rover',
    year: 2020,
    mileageKm: 46900,
    mileageLabel: '46,900 km',
    price: 11200000,
    priceLabel: 'KES 11,200,000',
    monthly: 185900,
    monthlyLabel: 'KES 185,900/mo',
    bodyType: 'SUV',
    fuel: 'Diesel',
    transmission: 'Automatic',
    drive: '4WD',
    image: '/images/vehicles/range-rover-sport.jpg',
    badges: ['Verified Mileage', 'Accident-Free'],
  },
  {
    id: 5,
    name: 'Audi Q7 55 TFSI',
    make: 'Audi',
    year: 2021,
    mileageKm: 35200,
    mileageLabel: '35,200 km',
    price: 9800000,
    priceLabel: 'KES 9,800,000',
    monthly: 162700,
    monthlyLabel: 'KES 162,700/mo',
    bodyType: 'SUV',
    fuel: 'Petrol',
    transmission: 'Automatic',
    drive: 'AWD',
    image: '/images/vehicles/audi-q7.jpg',
    badges: ['Verified Mileage', 'NTSA Cleared'],
  },
  {
    id: 6,
    name: 'Porsche Cayenne S',
    make: 'Porsche',
    year: 2020,
    mileageKm: 39800,
    mileageLabel: '39,800 km',
    price: 12600000,
    priceLabel: 'KES 12,600,000',
    monthly: 209100,
    monthlyLabel: 'KES 209,100/mo',
    bodyType: 'SUV',
    fuel: 'Petrol',
    transmission: 'Automatic',
    drive: 'AWD',
    image: '/images/vehicles/porsche-cayenne.jpg',
    badges: ['Verified Mileage', 'Service History'],
  },
  {
    id: 7,
    name: 'Toyota Harrier',
    make: 'Toyota',
    year: 2021,
    mileageKm: 44300,
    mileageLabel: '44,300 km',
    price: 5850000,
    priceLabel: 'KES 5,850,000',
    monthly: 97100,
    monthlyLabel: 'KES 97,100/mo',
    bodyType: 'SUV',
    fuel: 'Petrol',
    transmission: 'Automatic',
    drive: '2WD',
    image: '/images/vehicles/toyota-harrier.jpg',
    badges: ['Verified Mileage', 'NTSA Cleared'],
  },
  {
    id: 8,
    name: 'Mazda CX-5',
    make: 'Mazda',
    year: 2021,
    mileageKm: 39500,
    mileageLabel: '39,500 km',
    price: 4200000,
    priceLabel: 'KES 4,200,000',
    monthly: 69700,
    monthlyLabel: 'KES 69,700/mo',
    bodyType: 'SUV',
    fuel: 'Petrol',
    transmission: 'Automatic',
    drive: 'AWD',
    image: '/images/vehicles/mazda-cx5.jpg',
    badges: ['Verified Mileage', 'Service History'],
  },
  {
    id: 9,
    name: 'Subaru Forester XT',
    make: 'Subaru',
    year: 2020,
    mileageKm: 58200,
    mileageLabel: '58,200 km',
    price: 4650000,
    priceLabel: 'KES 4,650,000',
    monthly: 77200,
    monthlyLabel: 'KES 77,200/mo',
    bodyType: 'SUV',
    fuel: 'Petrol',
    transmission: 'Automatic',
    drive: 'AWD',
    image: '/images/vehicles/subaru-forester.jpg',
    badges: ['Verified Mileage', 'Accident-Free'],
  },
  {
    id: 10,
    name: 'Mercedes-Benz C200',
    make: 'Mercedes-Benz',
    year: 2021,
    mileageKm: 32800,
    mileageLabel: '32,800 km',
    price: 5900000,
    priceLabel: 'KES 5,900,000',
    monthly: 97900,
    monthlyLabel: 'KES 97,900/mo',
    bodyType: 'Sedan',
    fuel: 'Petrol',
    transmission: 'Automatic',
    drive: '2WD',
    image: '/images/vehicles/mercedes-c200.jpg',
    badges: ['Verified Mileage', 'NTSA Cleared'],
  },
  {
    id: 11,
    name: 'Toyota Hilux Double Cab',
    make: 'Toyota',
    year: 2020,
    mileageKm: 71400,
    mileageLabel: '71,400 km',
    price: 4850000,
    priceLabel: 'KES 4,850,000',
    monthly: 80500,
    monthlyLabel: 'KES 80,500/mo',
    bodyType: 'Pickup',
    fuel: 'Diesel',
    transmission: 'Manual',
    drive: '4WD',
    image: '/images/vehicles/toyota-hilux.jpg',
    badges: ['Verified Mileage', 'Locally Assembled'],
  },
  {
    id: 12,
    name: 'Volkswagen Golf GTI',
    make: 'Volkswagen',
    year: 2021,
    mileageKm: 29100,
    mileageLabel: '29,100 km',
    price: 4450000,
    priceLabel: 'KES 4,450,000',
    monthly: 73800,
    monthlyLabel: 'KES 73,800/mo',
    bodyType: 'Hatchback',
    fuel: 'Petrol',
    transmission: 'Automatic',
    drive: '2WD',
    image: '/images/vehicles/vw-golf-gti.jpg',
    badges: ['Verified Mileage', 'Service History'],
  },
  {
    id: 13,
    name: 'Nissan X-Trail',
    make: 'Nissan',
    year: 2020,
    mileageKm: 61700,
    mileageLabel: '61,700 km',
    price: 3950000,
    priceLabel: 'KES 3,950,000',
    monthly: 65500,
    monthlyLabel: 'KES 65,500/mo',
    bodyType: 'SUV',
    fuel: 'Petrol',
    transmission: 'Automatic',
    drive: 'AWD',
    image: '/images/vehicles/nissan-xtrail.jpg',
    badges: ['Verified Mileage', 'NTSA Cleared'],
  },
  {
    id: 14,
    name: 'Isuzu D-Max',
    make: 'Isuzu',
    year: 2021,
    mileageKm: 55900,
    mileageLabel: '55,900 km',
    price: 4300000,
    priceLabel: 'KES 4,300,000',
    monthly: 71400,
    monthlyLabel: 'KES 71,400/mo',
    bodyType: 'Pickup',
    fuel: 'Diesel',
    transmission: 'Manual',
    drive: '4WD',
    image: '/images/vehicles/isuzu-dmax.jpg',
    badges: ['Verified Mileage', 'Locally Assembled'],
  },
];

export const MAKES = Array.from(new Set(VEHICLES.map((v) => v.make))).sort();
export const BODY_TYPES: BodyType[] = ['SUV', 'Sedan', 'Pickup', 'Hatchback', 'Van'];
export const FUELS: Fuel[] = ['Petrol', 'Diesel', 'Hybrid', 'EV'];

export const PRICE_BRACKETS = [
  { label: 'All Prices', min: 0, max: Infinity },
  { label: 'Under KES 5M', min: 0, max: 5000000 },
  { label: 'KES 5M  8M', min: 5000000, max: 8000000 },
  { label: 'KES 8M  12M', min: 8000000, max: 12000000 },
  { label: 'KES 12M+', min: 12000000, max: Infinity },
];